server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/point-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update