server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

client:
  point-service:
    url: http://localhost:8082

jwt:
  secret: jwt-secret-1234-1234-1234-1234-1234-1234-1234-1234