server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

client:
  user-service:
    url: http://localhost:8080
  point-service:
    url: http://localhost:8082