server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1111

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

client:
  user-service:
    url: http://localhost:8080